### ISSUE TITLE
Definir como os dados de exemplo serão disponibilizados

### ISSUE THREAD

**Issue by gmgall** [Model-R/modelr_pkg#1]
Há 2 maneiras de disponibilizar dados num pacote R:

1) [exported data](http://r-pkgs.had.co.nz/data.html#data-data): usa-se essa forma para disponibilizar objetos R prontos para uso, como `data.frame`s e `RasterStack`s
1) [raw data](http://r-pkgs.had.co.nz/data.html#data-extdata): usa-se essa forma para disponibilizar os arquivos brutos, como arquivos CSV ou aqueles `.grd`s que lemos com `raster::stack()`

Usa-se a 2ª abordagem quando deseja-se mostrar como fazer o carregamento/*parsing* a partir dos dados brutos. Nesse caso, a função `system.file()` é usada para retornar o path do arquivo.

Optei pela 1ª maneira (1e18efe215328356bce88d1d1a7a532a042c3e5f) e por mostrar [o exemplo de como carregar os dados e usar as funções](https://gist.github.com/gmgall/1b240bcfe96022b6ed2f10470a710deb) nas *vignettes* (que ainda não escrevi).

Concordam com esse caminho? Tomei essa decisão unilateralmente porque o @gomesvilasboas quer fazer o commit de umas coisas e está só aguardando eu terminar isso. Se quiserem, eu mudo depois. Abri essa issue para ler a opinião de vocês.

**Comment by diogosbr** [comment]
Por mim tudo bem.

**Comment by FelipeSBarros** [comment]
Concordo tbm

**Comment by diogosbr** [comment]
Fiz um teste aqui e o objeto **`variaveis_preditoras`** não estava disponível, apareceu o seguinte erro:
```
> raster::plot(variaveis_preditoras$layer.1)
Error in file(fn, "rb") : cannot open the connection
In addition: Warning message:
In file(fn, "rb") :
  cannot open file '/home/guilherme/repos/ARF_spatial_planning/ENM/env/eigenvariables.gri': No such file or directory

> variaveis_preditoras$layer.1
class       : RasterLayer 
band        : 1  (of  6  bands)
dimensions  : 506, 528, 267168  (nrow, ncol, ncell)
resolution  : 0.1, 0.1  (x, y)
extent      : -83.64917, -30.84917, -37.07584, 13.52416  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
data source : /home/guilherme/repos/ARF_spatial_planning/ENM/env/eigenvariables.grd 
names       : layer.1 
values      : -27.9433, 3.384871  (min, max)
```

Os outros (**`coordenadas e mascara`**) eu consegui abrir tranquilo.

**Comment by AndreaSanchezTapia** [comment]
o problema é o path... acho que deveria ir numa pasta `data`

**Comment by diogosbr** [comment]
Mas tem um arquivo na pasta [/master/data](https://github.com/Model-R/modelr_pkg/tree/master/data). 
O arquivo até carrega, mas aponta para um path local. Não entendi o porque.

**Comment by AndreaSanchezTapia** [comment]
eu já vi isso alguma vez com rasters, como se na estrutura interna eles guardassem o path. tô pensando.

**Comment by diogosbr** [comment]
Eu criei um branch para mudar o objeto **`variaveis_preditoras`**.
Agora ele está na memória. 
```
> variaveis_preditoras$layer.1
class       : RasterLayer 
band        : 1  (of  6  bands)
dimensions  : 506, 528, 267168  (nrow, ncol, ncell)
resolution  : 0.1, 0.1  (x, y)
extent      : -83.64917, -30.84917, -37.07584, 13.52416  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
data source : in memory
names       : layer.1 
values      : -27.9433, 3.384871  (min, max)
```

Por favor, quem puder testar pra ver se está funcionando.

**Comment by gmgall** [comment]
Agora funciona. :clap: :clap: :clap: 

Usando seu branch

```R
> devtools::load_all()
Loading modelr
> raster::inMemory(variaveis_preditoras)
[1] TRUE
```

E o meu

```R
> devtools::load_all()
Loading modelr
> raster::inMemory(variaveis_preditoras)
[1] FALSE
```

Isso passou despercebido porque simplesmente testei  `class(variaveis_preditoras)` para ver se o objeto estava presente. Quando vi que estava, assumi que estava tudo OK sem verificar se os dados do raster estavam em memória ou não.
