### ISSUE TITLE
Parameter inheritance between functions

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [Model-R/modelr_pkg#30]
today 
everything inherits from setup_sdmdata, that has an ellipsis (...) for create_buffer.
organizar isto. 
test
create_buffer -> setup_sdmdata -> do_any -> do_enm -> final_model -> ensemble?

**Comment by saramortara** [comment]
all inheritance is now updated according to https://docs.google.com/spreadsheets/d/1BLfCYhiZLDhZqSd-KGLyzBeEe7Ov31m7ItH6SGdbPt0/edit#gid=0
