### ISSUE TITLE
Renomear Pacote

### ISSUE THREAD

**Issue by diogosbr** [Model-R/modelr_pkg#4]
Vamos eleger um nome para o pacote. Um nome que possa ser utilizado no CRAN.
A proposta que foi levantada há um tempo foi modelR (apenas com R maiúscula). 
Eu acho legal esse nome, mas a chance de 'confusão' com outro pacote (modelr), que já existe no CRAN, é grande. Ao mesmo tempo não sei se isso seria um problema. 
Por isso, abri esse issue, para fecharmos um nome e ficar documentado aqui.

**Comment by MFSiqueira** [comment]
Vou pensar nisso.
M.

Em 14 de dez de 2017 10:31, "Diogo S. B. Rocha" <notifications@github.com>
escreveu:

**Comment by diogosbr** [comment]
Olá Pessoal!
Hoje discutimos em reunião no LNCC um nome novo do pacote. 
ENModel

Todos concordam?

**Comment by lgadelha** [comment]
Sugeri também enmasse, que tem um toque de humor e remete um pouco a 
escalabilidade (em massa).

Abs,

---
Luiz Gadelha
http://www.lncc.br/~lgadelha

Em 2018-03-06 11:30, Diogo S. B. Rocha escreveu:

**Comment by diogosbr** [comment]
Então, as opções até agora são:
- ENModel
- ENMasse

Mais alguma sugestão?
@AndreaSanchezTapia ; @antunesmg ; @rafaeloliveiralima @renatacapellao
