### ISSUE TITLE
 Implementar 'rodadas' de partições. 

### ISSUE THREAD

**Issue by diogosbr** [Model-R/modelr_pkg#6]
Podemos implementar a possibilidade de fazer várias rodadas de partições, que seria equivalente a uma cross-validation com bootstrap. Pois, isso pode dar uma confiabilidade maior aos modelos finais. 

O procedimento é basicamente fazer os modelos das partições, em seguida criar novas partições e gerar os modelos.
Exemplo:
Temos 9 pontos e escolhemos fazer 3 partições, então, na primeira rodada temos:
- partition 1 = pts 1,2,3,
- partition 2 = pts 4,5,6
- partition 3 = pts 7,8,9

Na segunda rodada poderia ficar assim:

- partition 1 = pts 1,4,7,
- partition 2 = pts 2,5,8
- partition 3 = pts 3,6,9

E podemos repetir cada rodada diversas vezes. 
Desta forma, 5 algoritmos, 5 rodadas e 3 partições, teremos 5x5x3 = 75 modelos por espécie.

**Comment by MFSiqueira** [comment]
Gosto dessa ideia. É é importante pois o n baixo de partições que fazemos é
passível de crítica.
M.

Em 14 de dez de 2017 11:27, "Diogo S. B. Rocha" <notifications@github.com>
escreveu:
