### ISSUE TITLE
Usar pontos de pseudo-ausência balanceado para alguns algoritmos (e.g. RandomForest)

### ISSUE THREAD

**Issue by diogosbr** [Model-R/modelr_pkg#7]
Para alguns algoritmos (e.g. RF) o ideal é utilizar um número balanceado de pontos de presença e de pontos de ausência. Entretanto, no pacote usamos o mesmo número de ausências para todos os algoritmos. 
Então acho que podemos ir na função dos algoritmos que precisam de pontos balanceados e incluir linhas de comando para fazer uma sub-amostra dos pontos de pseudo-ausência com o mesmo número de pontos de presença.

**Comment by diogosbr** [comment]
@AndreaSanchezTapia, o que você acha?

**Comment by AndreaSanchezTapia** [comment]
Acho válido. Além disso de maneira geral gostaria de implementar um número variável de pseudo-ausências para cada espécie. Tínhamos testado 100x com Marinez, até 10000, por exemplo. 
Um problema que dá é que às vezes o n resultante é maior ao número de pixeis do raster, então precisaríamos ter um jeito de saber ou controlar esse valor. Isto acontece em particular quando há um buffer ativo (o buffer pode ser pequeno e o n de pixeis ser baixo, e a gente pedir um n.back muito alto) Isto gera um warning, mas não pára a rodada.
